### ISSUE TITLE
Cannot find gulp-util

### ISSUE THREAD

**Issue by Leobl** [amylily1011/gulp4-sass-bootstrap#1]
Hello after multiple tries I only get that output, so I cannot run the gulp file:

```
gulp style
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by amylily1011** [comment]
Hi @Leobl,

I don't have enough information for this issue. Have you tried following the steps on README.md?

There are 2 things I can recommend. 
1. If you are using older gulp version, you might need to install `gulp-util` in your dev env. But usually newer version will not require that.

2. You might also want to try reinstalling your project's local packages:

```
rm -rf node_modules/
npm install
```
